kind: IntegrationServer
apiVersion: appconnect.ibm.com/v1beta1
metadata:
  name: devops
  namespace: ace
spec:
  adminServerSecure: true
  createDashboardUsers: true
  designerFlowsOperationMode: disabled
  enableMetrics: true
  license:
    accept: true
    license: L-APEH-C9NCK6
    use: CloudPakForIntegrationProduction
  pod:
    containers:
      runtime:
        image: quay.io/vishwanath_puranik/ace-deploy-image-04:latest
        resources:
          limits:
            cpu: 300m
            memory: 350Mi
          requests:
            cpu: 300m
            memory: 300Mi
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  version: '12.0.4.0-r1'
