apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: run-devops-clone-delete-
  namespace: devops
spec: 
  taskRef:
    name: devops-clone-delete
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: dops-claim